// Command-line prompt:
// What would you like to do? (each time an option is chosen, the user is rerouted to this question)
//     - View all Employees ---> table with all employees
//     - Add Employees ----> "What is the employee's firs name?" ---> user input ---> "What is the employee's last name?" ---> user input ----> "What is the employee's role?"" ---> user input choices with all roles ---> "Who is the employees manager?"---> user input choices with all employees ---> "Added ${first name} ${last name} to the database"
//     - Update Employee Role ----> "which employees role would you like to update?" ---> user input choices with all employees ----> "which role would you like to assign them?" ---> user input choices with all roles ---> "updated employee role"
//     - View all role ---> table with all roles
//     - Add roles ---> "What is the name of the role?" ---> user input ---> "What is the Salary of the role?" ---> user input ---> "Which department does the role belong to?" ---> user input ---> "Added ${role} to the database"
//     - View all Departments ---> table with all departments 
//     - Add Department ---> "What is the name of the department?" ---> user input ---> "Added department to the database"
//     - Quit

// table 1:
// Employees- 
//  ID | first_name | last_name | title | department | salary | manager

    // ID:
    // Auto generated by integer

    // first_name:
    // Create yourself

    // last_name:
    // Create yourself

    // title:
    //    - Sales Lead
    //    - Salesperson
    //    - Lead Engineer
    //    - Account Manager
    //    - Legal Team Lead
    //    - Lawyer

    // Department:
    //    - Sales
    //    - Engineering
    //    - Finance 
    //    - Legal

    // Salary: Random Amount manually assigned

    // manager:
    // Create yourself




// table 2:
// Roles- 
//  ID | Title | Department | Salary

    // ID:
    // Auto generated by integer

    // title:
    //    - Sales Lead
    //    - Salesperson
    //    - Lead Engineer
    //    - Account Manager
    //    - Legal Team Lead
    //    - Lawyer

    // Department:
    //    - Sales
    //    - Engineering
    //    - Finance 
    //    - Legal

    // Salary: Random Amount manually assigned



// table 3:
// Department- 
// ID | Name

    // ID:
    // Auto generated by integer

    // Name:
    //    - Sales
    //    - Engineering
    //    - Finance 
    //    - Legal





// Steps:
    //  Check 1. Begin by creating the basic outline for each table 
    //  Check 2. Then create data to seed our tables with (employees, departments, roles)
    //  Check 3. Then create our query.sql to join the tabel information
    //  Check 4. Create a basic data flow for our index.js
    //  Check 5. write out questions for our command line following the video provided (follow team-profile structure)
    //  6. download all packages necessary to test code (in README)
    //  8. piece everything together

